1. create table person and position
melodiam16/University pull request #1
Opened 2024-12-03 20:18 UTC by melodiam16

2024-12-05 06:14 UTC, skalashynski requested changes

2024-12-05 06:14 UTC, skalashynski commented on 01-create-table.sql
> +	employee_id INTEGER PRIMARY KEY,
employee* для филдов не нужен, неправильно называть их так же как таблица.

2024-12-05 06:14 UTC, skalashynski commented on 01-create-table.sql
> +	employee_id INTEGER PRIMARY KEY,
для `id` лучше использовать тип UUID из большой стринги

2024-12-05 06:14 UTC, skalashynski commented on 01-create-table.sql
> +	ALTER COLUMN employee_position SET DATA TYPE VARCHAR(30);
На сегодняшний день пусть в скрипте будет `alter table`, но потом сразу создавай и коить нормальные поля в `create table`

2024-12-05 06:14 UTC, skalashynski commented on 01-create-table.sql
> +	CREATE TABLE job_position(
Просто `position` название таблицы

2024-12-05 06:14 UTC, skalashynski commented on 01-create-table.sql
> +	position_respons VARCHAR(30),
А что такое respons ? неправильное название колонки

2024-12-05 06:14 UTC, skalashynski commented on 01-create-table.sql
> +	SELECT * FROM employee;
`select` не нужен в этом файле. В этом файле создержатся только create and alter

2024-12-05 06:14 UTC, skalashynski commented on 02-insert-records.sql
> +
select в этом файле не нужен

2024-12-05 06:14 UTC, skalashynski commented on 02-insert-records.sql
> +	UPDATE employee
не совсем правильный скрипт. Обычно пищут 10 раз update с условиев `where id = x`

2024-12-06 20:01 UTC, melodiam16 commented on 01-create-table.sql
> +	employee_id INTEGER PRIMARY KEY,
виправлено

2024-12-07 14:47 UTC, skalashynski requested changes

2024-12-07 14:47 UTC, skalashynski commented on 01-create-table.sql
> +	ADD COLUMN email VARCHAR(320);
почему varchar (320) ?

2024-12-07 14:47 UTC, skalashynski commented on 01-create-table.sql
> +	obligation VARCHAR(30),
 в раельном мире, обязательства не прикрепляются к должности. Они больше относятся к человеку. У разных людей на 1ой должности могут быть разные обязательства. Кто-то приносит чай, а кто-то кофе.

2024-12-07 14:47 UTC, skalashynski commented on 01-create-table.sql
> +	salary NUMERIC CHECK(salary > 0)
Аналогочно обязательствам

2024-12-07 14:49 UTC, skalashynski requested changes

2024-12-07 14:49 UTC, skalashynski commented on 02-insert-records.sql
> +	(010, 'Elijah', 'Moore', 38, 2);
если у тебя тип uuid то неправильно будет указывать номер id сюда. Выясни что такое uuid и как его добавлять

2024-12-11 13:47 UTC, melodiam16 commented on 01-create-table.sql
> +	ADD COLUMN email VARCHAR(320);
стандарт RFC 5321/5322 для адрес електронної пошти. 
Локальна частина (до символу @) може бути до 64 символів.
Доменна частина (після @) може бути до 255 символів.
Разом: 64 + 1 (символ @) + 255 = 320 символів.
Використання максимальної довжини гарантує підтримку будь-якої дійсної адреси, яка відповідає стандартам

2024-12-11 14:10 UTC, melodiam16 commented on 02-insert-records.sql
> +	(010, 'Elijah', 'Moore', 38, 2);
виправлено

2024-12-11 14:11 UTC, melodiam16 commented on 01-create-table.sql
> +	salary NUMERIC CHECK(salary > 0)
виправлено

2024-12-11 14:11 UTC, melodiam16 commented on 01-create-table.sql
> +	obligation VARCHAR(30),
виправлено

2024-12-20 09:52 UTC, skalashynski commented on 01-create-table.sql
> +	ADD COLUMN email VARCHAR(320);
Молодец !

2024-12-30 18:43 UTC, merged